# Docker环境配置
server:
  port: 8080

# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接配置，使用环境变量或Docker网络名称
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ruoyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${SPRING_DATASOURCE_USERNAME:ruoyi}
    password: ${SPRING_DATASOURCE_PASSWORD:ruoyi123}
  
  redis:
    # Redis连接配置，使用环境变量或Docker网络名称
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    database: ${SPRING_REDIS_DATABASE:0}
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# 文件上传路径
ruoyi:
  profile: /app/uploadPath